---

- name: add tls certificate to /etc/ssl/
  ansible.builtin.copy:
    src: "files/primary/tls/{{ tls_cert_name }}"
    dest: "/etc/ssl/{{ tls_cert_name }}"
    owner: root 
    group: wheel
    mode: 0644
  when: tls_enable == True

- name: add tls key to /etc/ssl/
  ansible.builtin.copy:
    src: "files/primary/tls/{{ tls_key_name }}"
    dest: "/etc/ssl/private/{{ tls_key_name }}"
    owner: root
    group: wheel
    mode: 0600
  when: tls_enable == True
