---

- name: Ensure group "{{ user_masterdns_name }}" exists
  ansible.builtin.group:
    name: "{{ user_masterdns_name }}"
    state: present
  when: user_masterdns == True
    
- name: Ensure user "{{ user_masterdns_name }}" exists 
  user:
    name: "{{ user_masterdns_name }}"
    shell: /bin/ksh
    group: "{{ user_masterdns_name }}"
  when: user_masterdns == True
  
- name: create ~/.ssh dir for user "{{ user_masterdns_name }}"
  ansible.builtin.file:
    path: "{{ '/home/' + user_masterdns_name + '/.ssh' }}"
    state: directory
    owner: "{{ user_masterdns_name }}"
    group: "{{ user_masterdns_name }}"
    mode: 0700
  when: user_masterdns == True
  
- name: add authorized_keys for user "{{ user_masterdns_name }}"
  template:
    src: templates/masterdns_authorized_keys.j2
    dest: "{{ '/home/' + user_masterdns_name + '/.ssh/authorized_keys' }}"
    owner: "{{ user_masterdns_name }}"
    group: "{{ user_masterdns_name }}"
    mode: 0600
  when: user_masterdns == True
