---
 
- name: add the httpd.conf to /etc/
  ansible.builtin.template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd.conf
    owner: root
    group: wheel
    mode: 0644
  when: httpd_enable == True
  
- name: Enable service httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
  when: httpd_enable == True
  
- name: Enable service httpd
  ansible.builtin.service:
    name: httpd
    state: started
  when: httpd_enable == True
  
