---
#- include: networking.yaml
- include: kernel_params.yaml
- include: hostname.yaml
- include: pkg_path.yaml
- include: packages.yaml
- include: ntp.yaml
- include: user_main.yaml
- include: doas.yaml
- include: update_and_patch.yaml
- include: rc.conf.local.yaml
- include: iked.yaml
- include: ssl.yaml
- include: smtpd.yaml
- include: spamd.yaml
- include: dynamic_whitelist.yaml
- include: pf.yaml
- include: cron.yaml
- include: squid.yaml
- include: relayd.yaml
- include: httpd.yaml
- include: monitoring.yaml
- include: sync_website.yaml
- include: user_master_dns.yaml
- include: user_master_cert.yaml
- include: syslogd.yaml
- include: nsd.yaml
- include: ssh.yaml

#revoke root ssh access at the end
