---
- name: configure sshd_config from template
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel 
    mode: 0644

- name: restart sshd 
  ansible.builtin.service:
    name: sshd
    state: restarted   
