---

- name: Ensure group "{{ user_mastercert_name }}" exists
  ansible.builtin.group:
    name: "{{ user_mastercert_name }}"
    state: present
  when: user_mastercert == True

- name: Ensure user "{{ user_mastercert_name }}" exists 
  user:
    name: "{{ user_mastercert_name }}"
    shell: /bin/ksh
    group: "{{ user_mastercert_name }}"
  when: user_mastercert == True
  
- name: create ~/.ssh dir for user "{{ user_mastercert_name }}"
  ansible.builtin.file:
    path: "{{ '/home/' + user_mastercert_name + '/.ssh' }}"
    state: directory
    owner: "{{ user_mastercert_name }}"
    group: "{{ user_mastercert_name }}"
    mode: 0700
  when: user_mastercert == True
  
- name: add authorized_keys for user "{{ user_mastercert_name }}"
  template:
    src: templates/mastercert_authorized_keys.j2
    dest: "{{ '/home/' + user_mastercert_name + '/.ssh/authorized_keys' }}"
    owner: "{{ user_mastercert_name }}"
    group: "{{ user_mastercert_name }}"
    mode: 0600
  when: user_mastercert == True
